# Generated by Django 4.0.2 on 2022-02-13 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('etf_code', models.CharField(max_length=20, unique=True)),
                ('etf_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'etfs',
                'ordering': ('id',),
                'default_permissions': ('add', 'view', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'industries',
                'ordering': ('id',),
                'default_permissions': ('add', 'view'),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('market_name', models.CharField(choices=[('KOSPI', 'Kospi'), ('KOSDAQ', 'Kosdaq')], max_length=50, unique=True)),
            ],
            options={
                'db_table': 'markets',
                'ordering': ('id',),
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'sectors',
                'ordering': ('id',),
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=100, unique=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.industry')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.market')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.sector')),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ('id',),
                'default_permissions': ('add', 'view', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date', models.DateField(db_column='date')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.stock')),
            ],
            options={
                'db_table': 'stock_prices',
                'ordering': ('id',),
                'default_permissions': ('add', 'view', 'change'),
            },
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['sector_name'], name='index_sectors_sector_name'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['industry_name'], name='index_industries_industry_name'),
        ),
        migrations.AddField(
            model_name='etf',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.market'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock'], name='index_stock_prices_stock'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['market'], name='index_stocks_market'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='index_stocks_sector'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['industry'], name='index_stocks_industry'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['stock_code'], name='index_stocks_stock_code'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['stock_name'], name='index_stocks_stock_name'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('stock_code', 'stock_name')},
        ),
        migrations.AddIndex(
            model_name='etf',
            index=models.Index(fields=['etf_code'], name='index_etfs_etf_code'),
        ),
        migrations.AddIndex(
            model_name='etf',
            index=models.Index(fields=['etf_name'], name='index_etfs_etf_name'),
        ),
    ]
